import {
  siGmail,
  siGithub,
  siGitbook,
  siTelegram,
  siX,
} from "simple-icons";
import { siteConfig } from "./site";
import type { WidgetConfig } from "../types";

export const bentoWidgets: WidgetConfig[] = [
  {
    id: "clock",
    type: "clock",
    label: siteConfig.clock.label,
    timeZone: siteConfig.clock.timeZone,
    columns: 4,
    rows: 2,
    mColumns: 4,
    mRows: 2,
  },
  {
    id: "blog",
    type: "link",
    title: "Blog",
    description: "My Mindpalace",
    icon: siGitbook,
    href: "https://blog.eurekamxz.me/",
    columns: 2,
    rows: 2,
    mColumns: 2,
    mRows: 2,
  },
  {
    id: "github",
    type: "link",
    title: "GitHub",
    description: "EurekaMXZ",
    icon: siGithub,
    href: "https://github.com/EurekaMXZ",
    badgeLabel: "Follow",
    columns: 2,
    rows: 2,
    mColumns: 2,
    mRows: 2,
  },
  {
    id: "profile-counter",
    type: "image",
    src: "https://profile-counter.deno.dev/EurekaMXZ/count.svg",
    alt: "Profile counter",
    columns: 4,
    rows: 1,
    mColumns: 4,
    mRows: 1,
    backgroundColor: "#000000",
    backgroundSize: "contain",
    backgroundPosition: "center",
    padding: 10,
  },
  {
    id: "email",
    type: "link",
    title: "E-mail",
    description: siteConfig.profile.email,
    icon: siGmail,
    href: `mailto:${siteConfig.profile.email}`,
    columns: 4,
    rows: 1,
    mColumns: 4,
    mRows: 1,
  },
  {
    id: "telegram",
    type: "link",
    title: "Telegram",
    description: "Contact me on telegram",
    icon: siTelegram,
    href: "https://t.me/EurekaMXZ",
    columns: 2,
    rows: 2,
    mColumns: 2,
    mRows: 2,
  },
  {
    id: "x",
    type: "link",
    title: "X",
    description: "Follow me on X",
    icon: siX,
    href: "https://x.com/EurekaMXZ",
    columns: 2,
    rows: 2,
    mColumns: 2,
    mRows: 2,
  },
  {
    id: "github-stats",
    type: "image",
    src: "https://github-stats.eurekamxz.me/api?username=EurekaMXZ&show_icons=true&theme=dark&hide_border=true&include_all_commits=true&count_private=true&card_width=450px",
    alt: "GitHub stats card",
    columns: 4,
    rows: 2,
    mColumns: 4,
    mRows: 2,
    backgroundColor: "#161616",
    backgroundSize: "contain",
    backgroundPosition: "center",
  },
];
